### ISSUE TITLE
Getting the current assembly pass

### ISSUE THREAD

**Issue by Liniya** [z00m128/sjasmplus#114]
It would be nice if there was a built in variable to indicate the current assembly pass. Perhaps as a define (_PASS?), and/or a LUA variable/function (sj.pass?).

I know you can do it with LUA ALLPASS and "var = var + 1", but this isn't always convenient, and I just think it's one of these things that are better standardized.

**Comment by ped7g** [comment]
Added as `__PASS__`, along some other changes in the predefined defines:
http://z00m128.github.io/sjasmplus/documentation.html#s_predefined
