### ISSUE TITLE
Relocatable code

### ISSUE THREAD

**Issue by dr-slump-0** [z00m128/sjasmplus#118]
**Is your feature request related to a problem?**

I use DISP and ENT to define a code block to run on address distinct than the loaded address. The problem is when I need to access the execution address space before relocation from the load address space, I have to use a offset to access:
``` asm
		ORG $2000
dest_addr	EQU 35000
diff		EQU dest_addr-orig_addr
		...
		ld (savedSP-diff), sp
		...
		(RELOCATOR CODE)
		...
		call main
		ret
		...
orig_addr	DISP dest_addr
main		MODULE main
		...
savedSP		DW 0
		...
		ENT
```
The offset is diff.

**Describe the suggested solution:**

Would it be possible to add a pseudo operator that automatically adds this offset when we access an internal address from outside the DISP-ENT block? Ex: DISP_OFFSET
``` asm
		ORG $2000
dest_addr	EQU 35000
		...
		ld (DISP_OFFSET(savedSP)), sp
		...
		(RELOCATOR CODE)
		...
		call main
		ret
		...
		DISP dest_addr
main		MODULE main
		...
savedSP		DW 0
		...
		ENT
```
Thanks.

**Comment by ped7g** [comment]
Yes, I see multiple possibilities...

**A)** similarly to newly added `norel Label` operator I could add something like `nodisp Label` to get physical address of label (where the machine code did land).

cons: adds new operator keyword, bumps internal memory usage for labels table (both are very minor, maybe below "practically noticeable", but real)

**B)** similarly to `$` and `$$` add one more... :) ... `$$$`? To get "physical" address in `DISP` block. Then in your case you would do:
```
   ...
   ld (savedSPnodisp),sp
   ...

   ... (inside DISP block) ...
savedSPnodisp EQU $$$
savedSP       DW  0
```

cons: adds new operator keyword, although I don't think I will ever miss `$$$` for anything reasonable, plus it still allows for the physical page extension `$$$$` :D bwahaha.... (but seems to me somewhat logical, right? And low-risk/impossible of collision with legacy sources)
and requires manual definition of extra labels like `savedSPnodisp`, not allowing you to manipulate ANY label in disp block in this way, but only the designed ones.

At this moment I'm slightly leaning toward option "B", but I'm posting this to collect opinions and comments before doing final decision (your suggestion is "A" case of course) (or maybe even some "C" variant will be found).

----------------------------

possible workarounds for current sjasmplus:

- what you already did :)

- just relocate first, then patch... `ld (savedSP),sp` will then modify the already relocated code.

- define `struct` for multiple values, then in `DISP` block instantiate it as usual and create "non disp" alias for it:
```
    DISP 35000
; assume there is already defined `SomeStructure` with fields x,y,z
dataND SomeStructure = ($ - diff) ; define "non disp" alias
data   SomeStructure { 1, 2, 3 }  ; instantiate the data
    ENT
    ... usage outside of DISP ...
    ld (dataND.x),4
    (relocator)
    ld (data.y),5
    call main
```
This has the [dis]advantage of grouping the stuff you want to modify from outside together and having to add just one "diff" to get labels to all fields.

**Comment by dr-slump-0** [comment]
I think that simple solutions are better than complex artifacts. An operator to get physical address it's clearer.
