### ISSUE TITLE
Temp. labels doesn't work with LD and math operations doesn't applies to it

### ISSUE THREAD

**Issue by nihirash** [z00m128/sjasmplus#119]
**Code example**:
```
    MACRO EspCmd Text
    ld hl, 1F
    ld e, (2F - 1F)
    call ESPSend
    jr 2F
1   db Text
    db 13, 10 
2   
    ENDM
```

**Expected behavior**:
 * in HL loaded pointer to text
 * in e length of text+2
 * called sender rountine

**Real behavior**: 
```
error: Digit not in base: 1F
error: Digit not in base: 2F - 1F)
```

**Version**: SjASMPlus Z80 Cross-Assembler v1.15.0 (https://github.com/z00m128/sjasmplus)
**Operation system**: macOS Catalina 10.15.6

**Comment by ped7g** [comment]
yes, they work only for jumps/calls by how the code is designed.

They IMO can't be made part of expression evaluation, because the syntax does clash with binary numbers:
`ld hl,1b` -> this is `ld hl,0x01`. I don't see any good solution for this case.

BTW these are "temporary labels". "local labels" are the ones starting with dot, which gets prefixed with last non-local label, or with macro-instance prefix, i.e. your example can be rewritten as:
```
    MACRO EspCmd Text
    ld hl, .txtB
    ld e, (.txtE - .txtB)
    call ESPSend
    jr .txtE
.txtB: db Text
    db 13, 10 
.txtE:
    ENDM
```

**Comment by nihirash** [comment]
Sorry, I've confused them. 

Local labels doesn't solution cause I can have several same macros calls inside one main label.

**Comment by ped7g** [comment]
check the updated example... if that still doesn't help, show me some example with problem. :) We will hopefully sort it out somehow, once I better understand what is the problem.

**Comment by nihirash** [comment]
Wow! Thank you! 

Sorry for dumb bug!)

**Comment by ped7g** [comment]
You are welcome. Better ask than wasting hours on something what actually can be solved easily.

sjasmplus is kinda strange animal, it lacks in some areas (string operators, operator macros, N-pass assembling), but in other areas it has surprisingly powerful features leading often to quite complex and "unexpected" results, if you didn't spend 10 months fixing bugs in the implementation itself (and it can still sometimes surprise even me)... Don't be hard on yourself for misunderstanding some feature, they often have some non-obvious complexity and hidden power. I like about ~70% of the sjasmplus original design (and dislike about ~10% of it), but it actually takes lot of time to fully explore it and understand how it works.

And bug reports like **this** are still good material for other people, who may run into similar problem and wonder why temporary labels don't work in expressions... :) So thank you for reporting your issue. Have fun.
