### ISSUE TITLE
Incorrect detection of forward references in IF/IFN

### ISSUE THREAD

**Issue by specke** [z00m128/sjasmplus#123]
| Version 	| Platform 	| Topic 	|
|---------	|----------	|-------	|
|  v1.14.2 and higher |  Windows 10 | Incorrect detection of forward references in IF/IFN |

I have a piece of code which generates the warning about forward reference in IF/IFN, although all relevant symbols have been declared earlier. Version 1.4.1 (and earlier versions as well) accepts this code happily.

This is a trimmed version of my code:
```
		DEVICE ZXSPECTRUM48

	MODULE TestModule

		ORG 32768

Label1:	DS 100,0

@Label2:	EQU $

		DS 64

	IF	high Label2 > high Label1
		DISPLAY "not good"
	ELSE
		DISPLAY "good"
	ENDIF

	ENDMODULE
```
Unfortunately, this minimal example does not seem to replicate the behaviour of the full code. I'd be happy to share the full code privately, so that you can see the issue in your setup.

**Comment by ped7g** [comment]
I have sent you email.. waiting for full code. (the example code seems just fine, no idea so far what is happening)

**Comment by ped7g** [comment]
Got your email with source, the warning about forward reference happens on my machine too.
I see no reason for that, so I will investigate the sjasmplus, seems like a bug, thanks for reporting it.

Meanwhile if you add global prefix to the second label like this:
```
			IF	high cmCOPY > high @klLDI64
```
it will stop doing the warning (workaround if you want to get rid of it with current sjasmplus).

I will let you know after investigation, what is the result.

**Comment by ped7g** [comment]
Fixed. The warning in this special case is wrong, but benign, feel free to ignore it, until you upgrade to the fixed version, or use the workaround to avoid it.

The trigger is the instruction `jp klLDI64` ahead of `@klLDI64:` definition, so in internal structures there are two symbols `Kernel.klLDI64` (stays undefined forever, inserted by `jp`) and `klLDI64` defined well. The expression evaluator finds both, and does use the defined one, but the "undefined" warning remains from the other and is reported as forward reference. Another workaround is to do `jp @klLDI64` so the jump will not add extra symbol into internal tables.

But obviously the evaluator did need fix to not become confused in such case, and stop reporting the warning.
