### ISSUE TITLE
SAVETRD for Basic files with extra parameter `lengthwithoutvars`

### ISSUE THREAD

**Issue by ruguevara** [z00m128/sjasmplus#124]
**Is your feature request related to a problem?**
Problem: unability to SAVETRD a Basic file with Basic variables after the last Basic line, as SAVETAP is able to do.

**Describe the suggested solution:**
`SAVETRD <filename_of_trd_image>,<filename_in_trdos>,<address>,<length>[,<autorunline>[,<lengthwithoutvars>]]`

**Comment by ped7g** [comment]
Adding some zip file of TRD before writing such file, and after writing such file (to make sure the header data are written to disc image by sjasmplus the same way as TR-DOS does it) would be nice, and make this more likely to happen. (I'm myself unable to verify with real TR-DOS system, don't have any such machine + any knowledge, and I got burnt by the TRD docs already few times, so practical real-life example with files before/after are essential source of information how TR-DOS operates).

**Comment by FasterHLM** [comment]
[bug_savetrd.zip](https://github.com/z00m128/sjasmplus/files/6626964/bug_savetrd.zip)
Hi! Here's an example of the .trd image file you asked for: Boot1.B - has correct header date, Boot2.B - has incorrect header date.
