### ISSUE TITLE
z80 instruction params won't parse

### ISSUE THREAD

**Issue by zmajcenic** [z00m128/sjasmplus#125]
I must be doing something wrong on my Win 10 64-bit platform with the latest 1.17 build.
It simply won't compile anything and is throwing parse errors for the most basic things.

D:\MSX\msxdos_test>sjasmplus hello.asm --raw=hello.com
SjASMPlus Z80 Cross-Assembler v1.17.0 (https://github.com/z00m128/sjasmplus)
Pass 1 complete (0 errors)
Pass 2 complete (0 errors)
hello.asm(3): error: Unrecognized instruction: 0
hello.asm(3): error: Unexpected: 0
hello.asm(5): error: Unrecognized instruction: a,10h
Pass 3 complete
Errors: 3, warnings: 0, compiled: 7 lines, work time: 0.016 seconds

D:\MSX\msxdos_test>type hello.asm
; main

org 0
main:
ld a,10h
ret

If I remove a value for org then it fails with:
D:\MSX\msxdos_test>sjasmplus hello.asm --raw=hello.com
SjASMPlus Z80 Cross-Assembler v1.17.0 (https://github.com/z00m128/sjasmplus)
Pass 1 complete (0 errors)
Pass 2 complete (0 errors)
hello.asm(5): error: Unrecognized instruction: a,10h
Pass 3 complete
Errors: 1, warnings: 0, compiled: 7 lines, work time: 0.000 seconds

Is there some prereq required ?

**Comment by ped7g** [comment]
see the "Source file format" (below the CLI options paragraph):
http://z00m128.github.io/sjasmplus/documentation.html#s_cli

The instructions and directives can't start at beginning of line, only labels start there. So `org 0` becomes "org" label defined, and instruction "0" which is reported as syntax error.

You can use `--dirbol` to enable directives from beginning of line, but instructions can't be enabled in any way, so I would rather suggest to indent all "correctly" (like the classic assemblers with line divided into different parts starting at fixed columns)

**Comment by zmajcenic** [comment]
That's it ! I expected something silly like that. Thanks
