### ISSUE TITLE
STRUCT length

### ISSUE THREAD

**Issue by Truevideo** [z00m128/sjasmplus#126]
Hi, regarding the use of STRUCT  the manual (v1.17.0) states the following:

_When non zero offset is used, it acts as if BLOCK with length equal to offset was defined as first member of structure._

What's the rationale behind this behaviour? It's kind of counterintuitive that If I declare a STRUCT like this:

```
     STRUCT MYDATA,#8000
A1   BYTE
A2   BYTE
     ENDS
```
MYDATA ends up being equal to #8002 rather than 2 (the actual size of the fields declared), which is kind of a pointless value to have IMHO.

My guess is that it was implemented as a quick and dirty way to offset the values of the fields being declared, but that is messing up the length of the struct itself. 

In case this is the expected behaviour, is there any other way to get the actual size of a structure that is declared with an offset?

Thanks
J

**Comment by ped7g** [comment]
The offset works as block, so if you add block of #8000 at beginning, then size is #8002.
I guess it's meant as skipping some header in data/etc, if you want to define only later of the structure.

If you want size without offset, define the structure without offset.

If you are trying to place the structure at #8000 to have `A1` there, then declare the structure without offset and instantiate it at #8000:
```
     STRUCT S_MYDATA
A1   BYTE
A2   BYTE
     ENDS

MYDATA S_MYDATA = #8000
MYDATA2 S_MYDATA = #9000

    ld a,(MYDATA.A1) ; ld a,(#8000)
    ld a,(MYDATA2.A2) ; ld a,(#9001)
    ld bc,S_MYDATA  ; ld bc,2
    ld l,(ix+S_MYDATA.A2)  ; ld l,(ix+1)
   ; notice S_MYDATA vs MYDATA usage
   ; depending on if you use structure definition
   ; or particular instance
```

If you really need your original definition, then length = `MYDATA-MYDATA.A1`, but that's not how it's meant to be used.

**Comment by ped7g** [comment]
Closing because no further response plus issue is resolved from my side.
Feel free to reopen + add info if you don't agree.
