### ISSUE TITLE
Length-prefixed strings pseudo-op

### ISSUE THREAD

**Issue by sdsnatcher** [z00m128/sjasmplus#127]
I would like to suggest the addition of a pseudo-op for [length-prefixed](https://en.wikipedia.org/wiki/String_(computer_science)#Length-prefixed) strings to sjasmplus.

These are not easy to implement via macros, and while they can be implemented via Lua scripting, it becomes horribly cluttered when you have to mix sequences of normal strings and lpstrings, like:

```
 LUA
	function _lpstr (mystring)
	-- Implements lenght-prefixed strings
		_pl(" db '" .. string.pack("p", mystring) .. "'")
	end
 ENDLUA



	DZ	1,"string1"
 LUA ALLPASS
	_lpstring("lpstring1")
 ENDLUA	
	DZ	1,"stringz2"
 LUA ALLPASS
	_lpstring("lpstring2")
 ENDLUA	
	DZ	1,"stringz3"
 LUA ALLPASS
	_lpstring("lpstring3")
 ENDLUA	
	DZ	1,"stringz4"
 LUA ALLPASS
	_lpstring("lpstring4")
 ENDLUA	

```

It would be much cleaner to have something like:

```
	DZ	1,"string1"
	LPSB	"string1"
	DZ	1,"string2"
	LPSB	"string2"
	DZ	1,"string3"
	LPSB	"string3"
	DZ	1,"string4"
	LPSB	"string4"
```

Where LPSB would be the pseudo-op for "length-prefixed string with byte counter" and LPSW would be "length-prefixed string with word counter"

**Comment by sdsnatcher** [comment]
Either that, or even better the .strlen(string) pseudo-op of the CA65 assembler could be implemented. This way LPSB, LPSW or any other similar structure could be easily implemented with macros, like this:

```
.macro lpstring Str
 .byte .strlen(Str)
 .byte Str
.endmacro

```

**Comment by ped7g** [comment]
```
txt1:
.b: DZ .e-.b-1, "some string 1"
.e:
txt2:
.b: DZ .e-.b-1, "some string two"
.e:

; -> listing:
  1   0000              txt1:
  2   0000 0E 73 6F 6D  .b: DZ .e-.b-1, "some string 1"
  2   0004 65 20 73 74
  2   0008 72 69 6E 67
  2   000C 20 31 00
  3   000F              .e:
  4   000F              txt2:
  5   000F 10 73 6F 6D  .b: DZ .e-.b-1, "some string two"
  5   0013 65 20 73 74
  5   0017 72 69 6E 67
  5   001B 20 74 77 6F
  5   001F 00
  6   0020              .e:
```
A bit polluting label table, but works in current release and with/without `DEVICE` mode.
And you can technically hide it in macro:
```
lpstringz   MACRO string?
.b:         DZ .e-.b-1, string?
.e:
            ENDM
txt1  lpstringz "some string 1"
txt2  lpstringz "some string two"

; -> listing ->
  5   0000              txt1  lpstringz "some string 1"
  5   0000 0E 73 6F 6D >.b:         DZ .e-.b-1, "some string 1"
  5   0004 65 20 73 74 >
  5   0008 72 69 6E 67 >
  5   000C 20 31 00    >
  5   000F             >.e:
  6   000F              txt2  lpstringz "some string two"
  6   000F 10 73 6F 6D >.b:         DZ .e-.b-1, "some string two"
  6   0013 65 20 73 74 >
  6   0017 72 69 6E 67 >
  6   001B 20 74 77 6F >
  6   001F 00          >
  6   0020             >.e:
```

This will still hit limit of max 128 bytes emitted per single line, so you can't give the macro easily 128+ long string (and you would probably soon hit also other sjasmplus line limits expanding/substituting the arguments), so the word variant is kinda pointless, those super long strings would need to be done over multiple lines, so without macro wrapper (but still doable "manually").

And that's also what I don't completely like about your syntax proposal, it's not obvious where the `LPSB/LPSW` would search for the beginning of the string, to put length there. Plus in non-device mode it's impossible to modify already emitted machine code, so the assembler would need to somehow predict there will be LPSB later, and keep just buffering machine code without emit, which is like precisely what the sjasmplus is *not* doing currently and not designed to do (it's 3pass assembling, so in third pass the machine code is emitted as continuous stream of bytes and anything like this would need to be resolved in first two passes, and make somehow the third pass aware of it in advance = what the labels do in my examples above, those get set up during pass1/pass2, then pass3 knows what value to emit for length). (in device mode it's somewhat easier to just go back and modify the virtual memory, you can do that also easily in macros)

The string operators like `.strlen(..)` are definitely missing from current sjasmplus, one of the largest omissions. They could be somewhat worked around by using lua scripts, but it's often way too complex, would be handy to have at least some basic string operators available, for example to process also some version strings, etc.

**Comment by ped7g** [comment]
oh.. you probably put those `DZ 1,"...."` as examples of regular strings, not related to the new LPSB directive...
seem I misunderstood that part of your examples, sorry.

**Comment by ped7g** [comment]
so... are those macros enough for you and I can close this, or there's some issue with them?

**Comment by sdsnatcher** [comment]
Thanks for your help but, sadly, it didn't solve my problem because I really need to use strings longer than 128bytes.

I'll workaround with more LUA scripts for now, but it would be nice to both the string operators and longer DB string support as you mentioned. Maybe specific issues could be opened for those?

**Comment by ped7g** [comment]
if you need more than 128B, then the way without macro could be used with those manual labels as in the first example.

The string operators are mentioned in #71 

The 128B limit per line has no issue yet, but with current parser and internal implementation there's no reasonable way to make it limit-less-like. Raising the 128B limit to some other hard limit like 256 or 512 is probably not **that** difficult, but then you could have very long lines in the source code, which is basically wrong style and signals some deeper issue with how the project is being written+built.

If you need larger strings, you may want to consider binary input file with string already preprocessed for `incbin`, or using similar technique like the `lua_inctext` example, maybe adding second marker like ">>>" to define string label and do `db label.e-label-1` before processing text, and third marker "<<<" to define the `.e` label after string, etc..

Depends if you need rather tool to cover all possible cases (DZ/DC/..) or you need it for particular project with only null-terminated or only-bit7-terminated strings, you can optimize the type of markers and their implicit functionality.

The inctext example:
[lua_inctext.asm](/z00m128/sjasmplus/blob/master/tests/lua_examples/lua_inctext.asm)
[lua_inctext.lua](/z00m128/sjasmplus/blob/master/tests/lua_examples/lua_inctext.lua)
[test.txt](/z00m128/sjasmplus/blob/master/tests/lua_examples/lua_inctext/test.txt)
