### ISSUE TITLE
Update Lua to 5.3 or higher

### ISSUE THREAD

**Issue by sdsnatcher** [z00m128/sjasmplus#128]
SjASMPlus comes with Lua 5.1, but Lua 5.3 added features that are much useful for asm programming, like [bitwise operators](http://reader.epubee.com/books/mobile/b4/b47f786503455e927aad2845cef4c9ad/text00017.html) and functions to pack/unpack binary data.

It would be nice to have Lua updated to v5.3 or v5.4 then.

**Comment by ped7g** [comment]
duplicate of #73 ? (and "ETA" is unknown, needs rewriting of integration)

**Comment by sdsnatcher** [comment]
Oh, sorry. I missed that one.
