### ISSUE TITLE
dot-label inside IFUSED = error

### ISSUE THREAD

**Issue by sdsnatcher** [z00m128/sjasmplus#13]
When dot-labels (labels starting with a dot) are used inside IFUSED pseudo-op blocks, sjasmplus doesn't recognise them and spits out "Label not found" errors.

For example, the following code:

```
BAR:
 IFUSED
	ld	h,1
	ret
 ENDIF

NOTHING:
	ld	a,1
	ret

MYROUTINE:
 IFUSED
	ld	a,2
	or	a
	jr	z,.quit
	cp	3
	jr	c,.jump
	jr	.quit


 IFUSED	BAR
.jump:	ld	c,3
	jp	.quit
 ELSE
	ld	a,1
.jump:	ld	c,2
	jr	c,.quit
 ENDIF ; IFUSED BAR
	call	FOO
.quit:	ret

 ENDIF ; IFUSED MYROUTINE

	call	MYROUTINE
FOO:	call	BAR
	call	NOTHING
	ret
```

Trying to compile this code will result in the following errors:

```
$ sjasmplus labelBug.asm 
SjASMPlus Z80 Cross-Assembler v1.10.1 (https://github.com/z00m128/sjasmplus)
Pass 1 complete (0 errors)
Pass 2 complete (0 errors)
labelBug.asm(15): error: Label not found: MYROUTINE.quit
labelBug.asm(17): error: Label not found: MYROUTINE.jump
labelBug.asm(18): error: Label not found: MYROUTINE.quit
Pass 3 complete
Errors: 3, warnings: 0, compiled: 52 lines, work time: 0.000 seconds
```

Even the .quit label, that is outside of the IFUSED blocks, results in an error.

Note: The code accomplishes nothing. It's just an example.
Note2: Probably this bug happens with IF and IFUNUSED too.

**Comment by sdsnatcher** [comment]
BTW, I stopped using temporary labels long ago because they always have gone crazy at some point of the project. Maybe the temporary labels are affected by this bug too?

**Comment by z00m128** [comment]
Fixed by Busy in https://github.com/z00m128/sjasmplus/commit/8d57d2479fc3af787f8aa4b2f040dcde365ef373
