### ISSUE TITLE
Error compile LD (HL), C

### ISSUE THREAD

**Issue by DeadlyKom** [z00m128/sjasmplus#131]
| Version 	| Platform 	| Topic 	|
|---------	|----------	|-------	|
| v1.18.x 	| win 	| 	|

incorrect compilation LD (HL), C (#71)
replaces with LD (HL), #01 (#3601)

if you collect an 8-bit register with a lowercase letter, then everything is fine

PS Yes, and this code compiles when ok, and sometimes produces such a compilation.
      When inserting this macro, the first is normal, then erroneous, then again normal, strange behavior

**Comment by DeadlyKom** [comment]
19+  7514 2A F8 74    >                        LD HL, (FT_CMD_Address)
 19+  7517 11 00 00    >                        LD DE, (((2 << 24) | (((0) & 255) << 16) | (((0) & 255) << 8) | (((0) & 255) << 0)) >>  0) & 65535
 19+  751A 01 00 02    >                        LD BC, (((2 << 24) | (((0) & 255) << 16) | (((0) & 255) << 8) | (((0) & 255) << 0)) >> 16) & 65535
 19+  751D             >
 19+  751D 73          >                        LD (HL), E
 19+  751E 23          >                        INC HL
 19+  751F             >
 19+  751F 72          >                        LD (HL), D
 19+  7520 23          >                        INC HL
 19+  7521             >
 19+  7521 71          >                        LD (HL), C
 19+  7522 23          >                        INC HL
 19+  7523             >
 19+  7523 70          >                        LD (HL), B
 19+  7524 23          >                        INC HL
 19+  7525             >
 19+  7525 22 F8 74    >                        LD (FT_CMD_Address), HL
 20+  7528                                              FT_Clear 1, 1, 1
 20+  7528             >                        FT_CMD_Command ((38 << 24) | (((1) & 1) << 2 ) | (((1) & 1) << 1) | (((1) & 1) << 0))
 20+  7528 2A F8 74    >                        LD HL, (FT_CMD_Address)
 20+  752B 11 07 00    >                        LD DE, (((38 << 24) | (((1) & 1) << 2 ) | (((1) & 1) << 1) | (((1) & 1) << 0)) >>  0) & 65535
 20+  752E 01 00 26    >                        LD BC, (((38 << 24) | (((1) & 1) << 2 ) | (((1) & 1) << 1) | (((1) & 1) << 0)) >> 16) & 65535
 20+  7531             >
 20+  7531 73          >                        LD (HL), E
 20+  7532 23          >                        INC HL
 20+  7533             >
 20+  7533 72          >                        LD (HL), D
 20+  7534 23          >                        INC HL
 20+  7535             >
 20+  7535 36 01       >                        LD (HL), 1
 20+  7537 23          >                        INC HL
 20+  7538             >
 20+  7538 70          >                        LD (HL), B
 20+  7539 23          >                        INC HL
 20+  753A             >
 20+  753A 22 F8 74    >                        LD (FT_CMD_Address), HL

**Comment by ped7g** [comment]
You have probably macro argument named `C`, so it replaces the register with value.
Without showing me some source it's difficult to say.

But sjasmplus does see after DEFINE/macro-argument substitution `ld (hl),1`.

If it's macro argument name, then I would suggest to add question marks after it like:
```
  MACRO somemacro a?, b?, c?
    ld (hl),c
    ld (hl),c?
  ENDM

  somemacro 1, 2, 3
  somemacro 1, 2, c  ; btw this will assemble as "ld (hl),c"
```

**Comment by DeadlyKom** [comment]
and there is
this macro, broke everything
FT_Clear          macro C, S, T
                        FT_CMD_Command ((38 << 24) | (((C) & 1) << 2 ) | (((S) & 1) << 1) | (((T) & 1) << 0))
                        endm

replaced, on


FT_Clear          macro Color, Stencil, Tag
                        FT_CMD_Command ((38 << 24) | (((Color) & 1) << 2 ) | (((Stencil) & 1) << 1) | (((Tag) & 1) << 0))
                        endm

face palm ;D
