### ISSUE TITLE
__ERRORS__ define

### ISSUE THREAD

**Issue by ammehet** [z00m128/sjasmplus#135]
Errors: 2 but \_\_ERRORS\_\_ = 0. Is this OK?

SjASMPlus Z80 Cross-Assembler v1.18.1 (https://github.com/z00m128/sjasmplus)
test.asm(56): error: Forward reference
test.asm(77): error: Forward reference
Pass 1 complete (**_2 errors_**)
Pass 2 complete (**_2 errors_**)
\> --------- **_\_\_ERRORS\_\_ = 0x0000, 0_**
\> ------- \_\_WARNINGS\_\_ = 0x0000, 0
Pass 3 complete
**_Errors: 2_**, warnings: 0, compiled: 10665 lines, work time: 0.242 seconds

**Comment by ped7g** [comment]
no, that's bug. I think I see what is happening, the errors are in first pass, and the `__ERRORS__` gets probably reset during PassInit().

Thank you for report.
