### ISSUE TITLE
LUA function zx.trdimage_add_file broken

### ISSUE THREAD

**Issue by Liniya** [z00m128/sjasmplus#14]
According to the documentation, it is a function of 4 arguments, given as: "[void] zx.trdimage_add_file("filename", "somenameC", startaddress, length)".
However, if it is used that way, then the following error is returned

"error: [LUA] error in function 'trdimage_add_file'. argument #5 is '[no object]'; 'number' expected."

You can reproduce it like this (it works fine in the basic 1.07 RC7 SjASMPlus):

	DEVICE ZXSPECTRUM48

	LUA
	 zx.trdimage_create('test-trd.trd')
	 zx.trdimage_add_file('test-trd.trd','test.C',16384,255)
	ENDLUA

**Comment by mborik** [comment]
Hi Liniya, it's just a requirement of the fifth parameter which wasn't reflected into documentation by original author. 5th parameter is **autostart**, or so called *third parameter in header*:

```[void] zx.trdimage_add_file("filename", "somenameC", startaddress, length, autostart)```

So, I suggest to resolve this issue with simple update of [documentation.xml](docs/documentation.xml#L3039)

**Comment by Liniya** [comment]
Thank you for the clarification. I see now that this parameter is also supported for the SAVETRD function, although no error is given if it is omitted.

**Comment by mborik** [comment]
Sure, it will be much more meaningful if the parameter could be omitted (and it should be fixed in `lua_sjasm.cpp`) but for now, you can continue and develop 😉

**Comment by z00m128** [comment]
> So, I suggest to resolve this issue with simple update of [documentation.xml](https://github.com/z00m128/sjasmplus/blob/master/docs/documentation.xml#L3039)

It was updated in https://github.com/z00m128/sjasmplus/commit/51d9970ba23b80451fa58dbfa1fe1c1b7c9e0213.
