### ISSUE TITLE
segmentation fault with conditional dup/edup

### ISSUE THREAD

**Issue by dlancer** [z00m128/sjasmplus#146]
| Version 	| Platform 	| Topic 	|
|---------	|----------	|-------	|
| v1.18.2 	| macos bigSur 	|  dup/edup	|

Segmentation fault with conditional dup/edup:
```
sjasmplus test.asm 
SjASMPlus Z80 Cross-Assembler v1.18.2 (https://github.com/z00m128/sjasmplus)
[1]    71391 segmentation fault  sjasmplus test.asm
```

```asm
    org #8000

    define TEST_CRASH
test    
    ifdef TEST_CRASH
    dup 3
        ld  a, 0    
    else
        ld  a, 0
        ld  a, 0
        ld  a, 0
    endif
    ifdef TEST_CRASH 
    edup   
    endif
    ret
```

**Comment by ped7g** [comment]
Thank you. While it would be nice if sjasmplus would not hard-crash on this (and I will try to fix it), technically with current parser you can't cross-nest DUP-EDUP pair across multiple conditional statements, it must be nested in single block.

I don't think the crash-fix will help in this case (IMHO/IIRC it would require also serious change of parser to allow dup-block across several conditional blocks).

(I know your example is probably not your real code, as here it is trivial to collapse it to single block, but maybe you can still simplify your real code by using some macro/etc ... let me know if you struggle with rearrangement)
