### ISSUE TITLE
Variable Clash on v1.18.1 using windows 10

### ISSUE THREAD

**Issue by infromthecold** [z00m128/sjasmplus#152]
I have a define as 

define	PATH	"c:/Tx-1696/"

I create a equ 

COMMON_PATH:	equ	0 

The compiler thinks its 

COMMON_c:/Tx-1696/

F:\Projects\Komodo\Src\loader.asm(94): error: Invalid labelname: COMMON_"c
F:\Projects\Komodo\Src\loader.asm(94): error: Unrecognized instruction: /Tx-1696/":     equ     0

**Comment by ped7g** [comment]
yes, that's not bug, that's feature. Overly aggressive sub-word substitutions of DEFINEs.

If you have no use for this, you can since 1.18.3 completely disable sub-word substitutions `--syntax=s`
Or use non-clashing define names, like FILE_PATH vs COMMON_PATH

**Comment by infromthecold** [comment]
Yeah I have used non clashing names!
