### ISSUE TITLE
Macro arguments in LUA script

### ISSUE THREAD

**Issue by Truevideo** [z00m128/sjasmplus#153]
Is there any way to access macro arguments inside a LUA script? I mean something like this:

```
		MACRO _ENCODE STR,NUM

		LUA
		print(STR)
		print(NUM)
		ENDLUA

		ENDM

		_ENCODE "HELLO",4
```
Currently I'm getting nil as a result, which is kinda expected. 

I'm using version 1.18.3

Thank you

**Comment by ped7g** [comment]
yes, but not this directly, you need to work around it a bit.

Check these tests for examples of what works and what not:
https://github.com/z00m128/sjasmplus/blob/master/tests/lua_examples/lua_macro_arg2.asm
https://github.com/z00m128/sjasmplus/blob/master/tests/lua_examples/lua_macro_arg.asm

But I see in your example string, I'm less sure about those, I guess if you extract that through DEFINE -> sj.get_define, you could actually extract the string and work with it per char in lua? But generally sjasmplus has near zero support for string operations, except accepting them for DB/DW/... directives. So some friction is expected. But I think it should be possible to work around that, let me know if you are struggling with particular use case, and I will try myself.

**Comment by Truevideo** [comment]
Thanks for the quick reply, your suggestions worked beautifully. I actually need to work with strings so I opted for the DEFINE approach:

```
		MACRO _ENCODE STR

		DEFINE+	ARGDEF STR
		LUA
			x = sj.get_define("ARGDEF")
			for i = 1, #x do
				local c = string.sub(x,i,i)
				print(c)
			end
		ENDLUA

		ENDM

		_ENCODE ABC01234	// TEST STRING, NO QUOTES NEEDED
```

Regards

**Comment by ped7g** [comment]
closing this, as I don't see any "action" to do (and more aggressive substitutions in lua script are not on my roadmap, from quick one second consideration it feels unsafe, probably breaking other usage scenarios, and difficult to add).

Feel free to reopen if you think there is something to do to resolve this better.

**Comment by ped7g** [comment]
Reopening as after upgrade of lua and C bindings there's more room to tinker with current bindings safely, and the `sj.get_define` may be either extended or new `sj.get_macro_arg` can be introduced maybe... to be checked
