### ISSUE TITLE
incbin is not affected by disp

### ISSUE THREAD

**Issue by carlesoriol** [z00m128/sjasmplus#162]
incbin does not load binary in disp modified program counter.
```
	        DEVICE ZXSPECTRUM48
stack_top:  equ 0xffff
            org 0x8000
inici:      ; does not work
            ld de, 0x4000
            ld hl, screen
            ld bc, 6912
            ldir
            ; this works
            ld de, 0x4000
            ld hl, screen_around8000
            ld bc, 6912
            ldir
loop:       jr loop
screen_around8000:
            disp 0xc000
screen:     incbin "screens/fonstest.scr"
            endt

            SAVESNA "test.sna",inici
```

but there's nothing at 0xc000 (screen)

SjASMPlus Z80 Cross-Assembler v1.18.3, ubuntu linux

**Comment by ped7g** [comment]
yes, that's how it should work, ORG drives where machine code is produced (around 0x8000 in your example, including the incbin), DISP defines displacement to define labels "as if" the machine code was produced elsewhere.

So in your example `screen` label becomes 0xc000.

The expected usage looks more like:
```
  ; move data to their target DISP location from assembling ORG location
  ld hl,screen_around8000 ; where data are in SNA
  ld de,screen ; target area for which they are assembled
  ld bc,6912
  ldir ; move data to target location
```

If you want the incbin to land at 0xc000 during assembling, use another ORG, not disp

**Comment by carlesoriol** [comment]
Thanks. 
I misunderstood disp.
Is there any way to "push" the current org, move to another address and "pop" again to previous position?

**Comment by ped7g** [comment]
stack-like push/pop would be tricky to script, I guess it is doable, but not trivial (maybe the easiest way would be to use lua to script the stack), but somebody did ask me about section-like functionality where you switch between several sections with names like `section @code`, `section @data`, etc... and continuing in the particular section where you left:
https://github.com/z00m128/sjasmplus/blob/master/tests/macro_examples/section.asm

so maybe this example may work the way you like, or at least you may get idea how to create simple push/pop org with one level depth.

if this is of no help, and you really need something else, provide some example what you need and I may try to create some new example. :)

**Comment by carlesoriol** [comment]
Thanks for this amazing example, I'm sorry I didin't see it. 
It's so easy, like linking in C :-)

**Comment by ped7g** [comment]
closing this for the moment, feel free to reopen or create new issue if this doesn't resolve it for you.
