### ISSUE TITLE
Not An Issue - Just Requesting Help On Using MMU For Allowing "Full Ram" Mode On Spectrum NEXT.

### ISSUE THREAD

**Issue by AidyCC** [z00m128/sjasmplus#165]
Hello

Using sjasmplus, I am looking to use the whole 64k for my own code and I'm trying to emulate what is described [here.](http://dailly.blogspot.com/2018/10/advanced-programming-of-zx-spectrum-next.html?m=1)

My sample code is here:[main.asm.zip](https://github.com/z00m128/sjasmplus/files/7957808/main.asm.zip)
 
I'm sure what I'm trying to do is possible, it's just I can't seem to figure out the correct directives / parameters to use.  I think there's confusion with bank / page / slot terminology that isn't helping me either.

When I assemble this code and load the resulting .NEX file into my emulator (I'm using zesarux on Mac), I expect the border colour to continuoisly change colour.  The code works if I remove the Bank switching logic and just run it @0x8000.

Any help you can give me will be appreciated.

Thanks,

-Adrian

**Comment by AidyCC** [comment]
No worries - I finally figure it out.  It turned out I was launcing the .nex file with the wrong parameters.

All working now.

**Comment by ped7g** [comment]
Glad you worked it out. (I didn't check details of your zip file, and now I will skip if you resolved it).

Feel free to reopen or post new question, if you stumble on something else.

Some usage of `MMU` is described in the first chapter of "SpecBong" tutorial: https://github.com/ped7g/SpecBong/wiki

The all-ram mode is possible with Next just by using its regular MMU next-registers $50..$57, but keep in mind the default layout when new NEX file is loaded has ROM in bottom 16ki, so you must have initial setup code elsewhere, and bank RAM pages as you want them in code. But you can layout all of that in sjasmplus IMHO easily, that's the whole purpose of `MMU` directive and `$$label` operator.
