### ISSUE TITLE
Annoying "_" (underscore) related bugs

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [z00m128/sjasmplus#167]
another one f***n "_" related bug/feature

v1.17.0 ... v1.18.3

```
	defarray  test_array	1	;
	defarray+ test_array	2	;
test_array_var = 5
```

test.asm(1273): error: [ARRAY] Expression error: test_array_var = 5

**Comment by ped7g** [comment]
you mean v1.12.0 .. v1.18.2?

v1.18.3: "added `--syntax=s` mode to disable sub-word substitutions of DEFINEs"

```
# file opened: console_input
1     0000               opt --syntax=s
2     0000                      defarray  test_array    1       ;
3     0000                      defarray+ test_array    2       ;
4     0000              test_array_var = 5
5     0000
# file closed: console_input

Value    Label
------ - -----------------------------------------------------------
0x0005 X test_array_var
```

**Comment by NEO-SPECTRUMAN** [comment]
every batch file must contain --syntax=sdwtrer#$R#$fsdVSDV -Wno-<cdjffv> -Wno-<dvdjfd> -Wno-<fcnkst> -Wno-<idfvvdfd> -Wno-<irfefd>
?

**Comment by ped7g** [comment]
as you can see from my example, you can use `OPT` directive in the source itself
