### ISSUE TITLE
TURN OFF annoying warnings by default!

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [z00m128/sjasmplus#169]
`[rdlow]: Reading memory at low address: 0`
MUST be completely annihilated from sjasm source
it's completely stupid and useless
sjasm used for many platforms
many spectums has ram at $0000...
its write to $0000 may mean mistake 
NOT READ 🤦 

some coders in principle still using 1.07 RC7
due to the useless permanent warningflow of the z00m's sjasm...

**Comment by NEO-SPECTRUMAN** [comment]
> some coders in principle still using 1.07 RC7
> due to the useless permanent warningflow of the z00m's sjasm...

наглядный пример
![2022-02-16_181009](https://user-images.githubusercontent.com/88002487/154304943-ba8a6e92-f33e-41d0-b96b-dc3e531fc61d.png)

**Comment by NEO-SPECTRUMAN** [comment]
--msg=war will block useful warnings

**Comment by NEO-SPECTRUMAN** [comment]
warning[luamc]: When lua script emits machine code bytes, use "ALLPASS" modifier

in 1.18.3+ "ok" plug will be disabled?
luamc - means only "When lua script emits machine code bytes, use "ALLPASS" modifier" message?

**Comment by ped7g** [comment]
Just to clarify:
`--msg=war` doesn't block any warning, it removes extra info about included binary files, etc.
`--msg=err` removes all warnings and keeps only errors.

the "ok" deprecation means the ok has to be prefixed with warning id which you want to suppress:
```
  LUA PASS3  ; luamc-ok ; <- this will suppress only "luamc" warning, no other
     _pc("db 256")
  ENDLUA
```
this will still warn about value 256 being truncated, but machinecode warning will be suppressed.
