### ISSUE TITLE
There is also a very old fork of same sourceforge...

### ISSUE THREAD

**Issue by adlogic** [z00m128/sjasmplus#17]
https://github.com/sjasmplus/sjasmplus

Maybe you can cooperate somehow? As it seems you both are fixing same things...

**Comment by z00m128** [comment]
I think no one of us did not know it exists until now. This is the freedom and risks of open source software. There are too many differences now to join the projects. We are trying to do it on the fly as we find the bugs. Then keeping docs updated and making fresh regular releases with windows builds for users who did not know how to build it for themselves. The other project looks more or less personal thing to me as the last release was more than a year ago (no offence).  Maybe I'm wrong, but we can inspire each other at least ;-)
