### ISSUE TITLE
DECLARING ARRAY WITHOUT [DEFARRAY] must have at least one entry

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [z00m128/sjasmplus#175]
defarray -id- without -replacements- must declaring empty array!
(for adding with defarray+ later)

**Comment by ped7g** [comment]
empty arrays are not possible with current implementation (empty array = regular define, but then you can't convert it to array later).

you can maybe work-around this by adding dummy first value, and index from 1+ for the other added values?

**Comment by ped7g** [comment]
closing this for now, as there's no chance to implement this without internal architecture rewrite/change, and the benefit doesn't seem to be worth that.
