### ISSUE TITLE
1.19.0 from releases doesn't run at all

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [z00m128/sjasmplus#178]
1.19.0 from releases doesn't run at all
without any messages
custom build looks like works

**Comment by ped7g** [comment]
what platform? if windows, did you check your antivirus, etc? what does it do when you just run it from command line?

**Comment by NEO-SPECTRUMAN** [comment]
win XP

> what does it do when you just run it from command line?

it do nothing at all
like return 0
![2022-05-10_031849](https://user-images.githubusercontent.com/88002487/167518704-76f3c66e-8f82-46e6-8b58-27048858b058.png)

did you change/update compiller?

**Comment by ped7g** [comment]
> did you change/update compiller?

me? :D .. I don't have any windows for like 15 years... (and I do get newer versions of compilers like every few months or so, but I just keep my linux updated all the time).

Do you use some antivirus? Did you check it's logs/history/something? The sjasmplus is UPX packed.

Assigning to z00m as he's building the .exe, but not sure if we have some WinXP machine to verify if the new exe still works.

**Comment by NEO-SPECTRUMAN** [comment]
i will try check it in virtualbox vitout AV
my AV usualy always display something
(not silent blocking)

**Comment by NEO-SPECTRUMAN** [comment]
it doesn't run on XP
it doesn't run on ReactOS

it runs on XP with OCAPI 2.2.1 (win15 subsystem for XP)

looks like XP has droped in the compiller

**Comment by NEO-SPECTRUMAN** [comment]
>edit: also I asked you to show length/content.. at least DIR sjasmplus.exe, if you don't have some simple hex-dump tool

I can't translate/understand this
it sounds like some about dir path to exe or other files in sjasm folder
but what does a hex dump tool have to do with it? o_O


i can do some like this

from releases
![2022-05-10_054020](https://user-images.githubusercontent.com/88002487/167533113-f3c0db02-f349-4757-b1f1-b22ce80846fc.png)

my build
![2022-05-10_054003](https://user-images.githubusercontent.com/88002487/167533137-06a785be-5249-4cc5-a7c7-32979ee91676.png)

from releases
`
Started "SJASMPLUS.EXE" (process 0x6A6C) at address 0x00400000.  Successfully hooked module.
Loaded "NTDLL.DLL" at address 0x7C900000.  Successfully hooked module.
Loaded "KERNEL32.DLL" at address 0x7C800000.  Successfully hooked module.
DllMain(0x7C900000, DLL_PROCESS_ATTACH, 0x00000000) in "NTDLL.DLL" called.
DllMain(0x7C900000, DLL_PROCESS_ATTACH, 0x00000000) in "NTDLL.DLL" returned 1 (0x1).
DllMain(0x7C800000, DLL_PROCESS_ATTACH, 0x00000000) in "KERNEL32.DLL" called.
DllMain(0x7C800000, DLL_PROCESS_ATTACH, 0x00000000) in "KERNEL32.DLL" returned 1 (0x1).
Injected "DEPENDS.DLL" at address 0x08370000.
DllMain(0x08370000, DLL_PROCESS_ATTACH, 0x00000000) in "DEPENDS.DLL" called.
DllMain(0x08370000, DLL_PROCESS_ATTACH, 0x00000000) in "DEPENDS.DLL" returned 1 (0x1).
Loaded "MSVCRT.DLL" at address 0x77C00000.  Successfully hooked module.
Entrypoint reached. All implicit modules have been loaded.
DllMain(0x77C00000, DLL_PROCESS_ATTACH, 0x0022FD30) in "MSVCRT.DLL" called.
GetProcAddress(0x7C800000 [KERNEL32.DLL], "InitializeCriticalSectionAndSpinCount") called from "MSVCRT.DLL" at address 0x77C279C2 and returned 0x7C80B8C9.
DllMain(0x77C00000, DLL_PROCESS_ATTACH, 0x0022FD30) in "MSVCRT.DLL" returned 1 (0x1).
DllMain(0x77C00000, DLL_PROCESS_DETACH, 0x00000001) in "MSVCRT.DLL" called.
DllMain(0x77C00000, DLL_PROCESS_DETACH, 0x00000001) in "MSVCRT.DLL" returned 1 (0x1).
DllMain(0x08370000, DLL_PROCESS_DETACH, 0x00000001) in "DEPENDS.DLL" called.
DllMain(0x08370000, DLL_PROCESS_DETACH, 0x00000001) in "DEPENDS.DLL" returned 1 (0x1).
DllMain(0x7C800000, DLL_PROCESS_DETACH, 0x00000001) in "KERNEL32.DLL" called.
DllMain(0x7C800000, DLL_PROCESS_DETACH, 0x00000001) in "KERNEL32.DLL" returned 1 (0x1).
DllMain(0x7C900000, DLL_PROCESS_DETACH, 0x00000001) in "NTDLL.DLL" called.
DllMain(0x7C900000, DLL_PROCESS_DETACH, 0x00000001) in "NTDLL.DLL" returned 1 (0x1).
Exited "SJASMPLUS.EXE" (process 0x6A6C) with code 0 (0x0).
`


my build
`
Started "SJASMPLUS_1_19_0_NS_BUILD.EXE" (process 0x751C) at address 0x00400000.  Successfully hooked module.
Loaded "NTDLL.DLL" at address 0x7C900000.  Successfully hooked module.
Loaded "KERNEL32.DLL" at address 0x7C800000.  Successfully hooked module.
DllMain(0x7C900000, DLL_PROCESS_ATTACH, 0x00000000) in "NTDLL.DLL" called.
DllMain(0x7C900000, DLL_PROCESS_ATTACH, 0x00000000) in "NTDLL.DLL" returned 1 (0x1).
DllMain(0x7C800000, DLL_PROCESS_ATTACH, 0x00000000) in "KERNEL32.DLL" called.
DllMain(0x7C800000, DLL_PROCESS_ATTACH, 0x00000000) in "KERNEL32.DLL" returned 1 (0x1).
Injected "DEPENDS.DLL" at address 0x08370000.
DllMain(0x08370000, DLL_PROCESS_ATTACH, 0x00000000) in "DEPENDS.DLL" called.
DllMain(0x08370000, DLL_PROCESS_ATTACH, 0x00000000) in "DEPENDS.DLL" returned 1 (0x1).
Loaded "MSVCRT.DLL" at address 0x77C00000.  Successfully hooked module.
Entrypoint reached. All implicit modules have been loaded.
DllMain(0x77C00000, DLL_PROCESS_ATTACH, 0x0022FD30) in "MSVCRT.DLL" called.
GetProcAddress(0x7C800000 [KERNEL32.DLL], "InitializeCriticalSectionAndSpinCount") called from "MSVCRT.DLL" at address 0x77C279C2 and returned 0x7C80B8C9.
DllMain(0x77C00000, DLL_PROCESS_ATTACH, 0x0022FD30) in "MSVCRT.DLL" returned 1 (0x1).
DllMain(0x77C00000, DLL_PROCESS_DETACH, 0x00000001) in "MSVCRT.DLL" called.
DllMain(0x77C00000, DLL_PROCESS_DETACH, 0x00000001) in "MSVCRT.DLL" returned 1 (0x1).
DllMain(0x08370000, DLL_PROCESS_DETACH, 0x00000001) in "DEPENDS.DLL" called.
DllMain(0x08370000, DLL_PROCESS_DETACH, 0x00000001) in "DEPENDS.DLL" returned 1 (0x1).
DllMain(0x7C800000, DLL_PROCESS_DETACH, 0x00000001) in "KERNEL32.DLL" called.
DllMain(0x7C800000, DLL_PROCESS_DETACH, 0x00000001) in "KERNEL32.DLL" returned 1 (0x1).
DllMain(0x7C900000, DLL_PROCESS_DETACH, 0x00000001) in "NTDLL.DLL" called.
DllMain(0x7C900000, DLL_PROCESS_DETACH, 0x00000001) in "NTDLL.DLL" returned 1 (0x1).
Exited "SJASMPLUS_1_19_0_NS_BUILD.EXE" (process 0x751C) with code 1 (0x1).
`

in log only the exit code differs

**Comment by NEO-SPECTRUMAN** [comment]
Can this cause external exe packer?

**Comment by z00m128** [comment]
> did you change/update compiller?

The toolchain is same for years: Win10 Pro 64bit, MinGW 32bit, and UPX 3.96 and was not updated, except windows updates. Could be that 21H2 feature update changed the corresponding API. I don't know.

>Can this cause external exe packer?

Most likely not, as it is used from the beginning of our fork.

I don't use windows either. Windows XP is an unsupported operating system for 13 years. I don't have a Windows XP computer, I don't have any installation media anymore and I don't feel like downloading some from the internet, which will be infected with who knows what, and then struggling with antivirus to build the clean sjasmplus binary. Sorry, I don't have time for that, so closing this as Windows XP not supported.

**Comment by NEO-SPECTRUMAN** [comment]
:rofl:

**Comment by ped7g** [comment]
according to Busy there's `btowc` function call in `msvcrt.dll` which is not supported on XP, so I guess from 1.19.0 onward the official exe will not work on WinXP.

**Comment by z00m128** [comment]
Try new build made in ReactOS. Should work with Windows XP and 2003.
https://github.com/z00m128/sjasmplus/releases/download/v1.19.0/sjasmplus-1.19.0.winxp.zip
