### ISSUE TITLE
lua integration is broken since at least v1.10.4, the external libs for bitwise/hex conversion don't init (`LUA_ERRSYNTAX`)

### ISSUE THREAD

**Issue by ped7g** [z00m128/sjasmplus#181]
the `tolua++` function `tolua_dobuffer` will silently fail, so this went unnoticed for years, but the binary-blobs are probably incompatible with current lua 5.1 interpreter and needs proper refresh, re-generating the lua_sjasm.cpp again from the .pkg file.

See also related #73, maybe upgrade whole lua to newer version and rework the integration?

**Comment by NEO-SPECTRUMAN** [comment]
the main problem is the lack of available commands description (in sjasm)
i try many commands finded in internet but it doesn't work
bitwise operations maybe too
for simple operations i was forced to use very not rational code...
