### ISSUE TITLE
ZX Next Device

### ISSUE THREAD

**Issue by maziac** [z00m128/sjasmplus#19]
Are you planning to support the ZX Next as DEVICE (similar to ZXSPECTRUM128) in the near future?

**Comment by z00m128** [comment]
As far as I know, this feature is not planned in the future, as there are alternative products which supports that.

**Comment by ped7g** [comment]
(adding some notes, to use this issue as a idea-tracker in case I will focus on this)

There is now full support for Z80N instructions (as of core2.00.26+).
So the missing parts are I guess:
- `DEVICE` directive, and memory model of Next
- Copper instructions support (not sure what would be best fit, as there are many different ways how one can actually write the source for copper "code")? ... probably some macro/constants includes with different variants would be better than built-in support
- `NEX` file format support ( https://gitlab.com/thesmog358/tbblue/blob/master/src/c/NexCreator.c ), maybe some other file format too (seems like "everyone" is designing their own :/ )
- ??? anything else ??? (feel free to add suggestion + reasoning)

**Comment by ped7g** [comment]
`DEVICE` is now supported, memory model is supported (new directives `MMU` and `SAVEDEV` to make manipulation of larger blocks of device memory simpler and safer).

`SAVENEX` is coming soon.

Can't think of anything else "essential", so after finalizing these I will consider this one "done".

**Comment by ped7g** [comment]
The v1.13.0 (to be released soon) has now what I consider "complete basic" support of ZX Spectrum Next machine - all instructions, memory model and the NEX file format support.

At this moment I have no further idea what else is essential enough to be added directly into sjasmplus (as many things can be resolved well through the powerful macros and making them even more powerful is probably next focus), so open Issue if you run into some problem or you have some idea.
