### ISSUE TITLE
WTF Dup bug

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [z00m128/sjasmplus#192]
at least 1.18.3 .. .1.20.1

```
	dup 3	
1
		dup 5
		nop
		edup
		djnz 1b
	
	edup
```

this is ok
 
...
 
```
	dup 3	
1		dup 5
		nop
		edup
		djnz 1b
	
	edup
```

this is

error: [EDUP/ENDR/ENDW] End repeat without repeat
error: [DUP/REPT] missing EDUP/ENDR to end repeat-block

**Comment by NEO-SPECTRUMAN** [comment]
looks like label + dup on same line is valid syntax but...

**Comment by ped7g** [comment]
debug info for myself, colon-split works:
```
 dup 3
1 : dup 2 : nop : edup : djnz 1b : edup
```

so only label + dup fails when already inside dup block (first level without nesting works too).

Must be the specialised parser routine looking for edup being confused by labels.
