### ISSUE TITLE
Interest in adding a new Z80 device ? VZ200/Laser210

### ISSUE THREAD

**Issue by bushy555** [z00m128/sjasmplus#213]
**Describe the suggested solution:**

Proposal: adding the Video Tech VZ200 / Laser210 computer to the current list of output devices for SJASMPlus.
I personally already use SJASM for creating binaries for this computer.
It would simply be a matter of creating the VZ/Laser 24 byte header when the "DEVICE" mnemonic is used in the header of the source code, such as "DEVICE VZ200".

$7B00 is the standard location for all self-executing binaries to start in the VZ / Laser computer. This is for all 2Kb, 6Kb and 16Kb machines.
$8000 is the location that I personally use all the time. Just personal preference. Does limit memory for 2Kb machines though.

The VZ/Laser header, for all executable binary files is:

----------------------
; VZ/Laser generic header for the .VZ snapshot file. 
; Works in all emulators as well as all hardware via loading in as a .WAV file.
; Note the first four bytes possibly should be "VZF1" as the further below examples indicate, however, in this working example, they are not necessary. Two spaces and two nulls work quite satisfactory on real hardware.

	org 	$7B00 - 24		
	db 	$20, $20, $00, $00, $56, $5A, $46, $49, $4c, $45, $00, $00	
	db 	$00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $F1		
	dw	start

	ORG 	$7B00
start equ $

----------------------

A breakdown of this : 

typedef struct vzFile {
	byte vzmagic[4];
	byte filename[17];
	byte ftype;
	byte start_addrl;
	byte start_addrh;
} VZFILE;

In ASM:
	org	$7B00-24
	defb	  'VZF1'			; HEADER: vzmagic        [04].
	defb	  'VZFILE.VZ        ' 	; HEADER: filename        [17].
	defb	  $F1			; HEADER: Filetype         [01].
	defw   $7B00		        ; HEADER: Start address [02].

===

This is what the MPAGD game creator uses as its real working header for the VZ/Laser computers.

; Code for header to create a .vz file
	defb 'VZF1'
	defb 'AGDGAME',0,0,0,0,0,0,0,0,0,0
	defb $f1
	defb $00 ; lb $7b00
	defb $7b ; hb $7b00
	org $7b00
        ; start of game.

**Comment by bushy555** [comment]
Actually, this might be slightly tidier:


ORIGIN equ $7B00

   org 	ORIGIN - 24		
db 	$20, $20, $00, $00, $56, $5A, $46, $49, $4c, $45, $00, $00	
db 	$00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $F1		
dw	start

   org 	ORIGIN
start equ $

 ; start of program

**Comment by ped7g** [comment]
I believe you use the terminology a bit differently than I'm used to, the `DEVICE` usually deals with memory mapping (related to `SLOT, PAGE, MMU` directives) and initial state of virtual memory. Judging by your info it looks like the VZ200 fits into any of current devices (use `NOSLOT64K` for example), although I see on wiki info about external banked memory expansion, but no idea how big it is, and what is the memory map when using it. 

And binary header for VZ file is more related to directives like `SAVE3DOS,SAVEAMSDOS,SAVECDT,SAVECPCSNA,...`

As the header is rather trivial without any extra functionality (some checksum byte, another binary tag at end of file, etc.), I would for the moment suggest to continue the way you are already doing it, putting the header 24 bytes ahead of the real binary, and `SAVEBIN/OUTPUT` it whole.

To make this less error prone I would suggest to use some general include file across projects defining the header as `STRUCT` like this:
```
    STRUCT VZ200FILEHEADER
magic   TEXT 4, { "VZF1" }
fname   TEXT 17
ftype   BYTE $F1
start   WORD $8000
    ENDS
```

then you can use it in your code like this:
```
    ORG $7B00 - VZ200FILEHEADER
    OUTPUT "VZFILE.VZ"
    VZ200FILEHEADER { , { "VZFILE" }, , start } // default magic and ftype, custom fname and start
start:
    jp $
    OUTEND
```

hexdump of resulting file:
```
$ hd VZFILE.VZ 
00000000  56 5a 46 31 56 5a 46 49  4c 45 00 00 00 00 00 00  |VZF1VZFILE......|
00000010  00 00 00 00 00 f1 00 7b  c3 00 7b                 |.......{..{|
0000001b
```

listing from sjasmplus:
```
# file opened: vz200_file_header.asm
 1    0000                  STRUCT VZ200FILEHEADER
 2    0000 ~            magic   TEXT 4, { "VZF1" }
 3    0000 ~            fname   TEXT 17
 4    0000 ~            ftype   BYTE $F1
 5    0000 ~            start   WORD $8000
 6    0000                  ENDS
 7    0000
 8    0000                  ORG $7B00 - VZ200FILEHEADER
 9    7AE8                  OUTPUT "VZFILE.VZ"
10    7AE8 56 5A 46 31      VZ200FILEHEADER { , { "VZFILE" }, , start } // default magic and ftype, custom fname and start
10    7AEC 56 5A 46 49
10    7AF0 4C 45 00 00
10    7AF4 00 00 00 00
10    7AF8 00 00 00 00
10    7AFC 00 F1 00 7B
11    7B00              start:
12    7B00 C3 00 7B         jp $
13    7B03                  OUTEND
14    7B03
# file closed: vz200_file_header.asm

Value    Label
------ - -----------------------------------------------------------
0x7B00   start
0x0018   VZ200FILEHEADER
0x0004 X VZ200FILEHEADER.fname
0x0015 X VZ200FILEHEADER.ftype
0x0000 X VZ200FILEHEADER.magic
0x0016 X VZ200FILEHEADER.start
```

The point of this syntax sugar is to minimize magic numbers like `-24` to avoid opportunities for some typo-bugs, etc.

At this moment I believe there's not much to gain by incorporating this into sjasmplus binary as specialized `SAVEVZ`, so I'm closing this as won't fix, but feel free to reopen if you think there is more VZ specific stuff which would justify new device or save command (like if you will collect technical info about memory banking and it would not match any other device, that would be a good reason to add new device with banking scheme matching VZ200).

**Comment by ped7g** [comment]
I will add this short example as test in the git, so it may appear later if anyone will search for VZ200 and sjasmplus, I guess this feels trivial for me, but could be show stopper for somebody beginning with Z80 assembly and not being very familiar with how assembler and binary files work, so hopefully test-example will cover these.

If there is some VZ200 fan hub with tutorials, it may be worth to add some example project there, let me know if there is such web and how to contribute to it?
