### ISSUE TITLE
duplicate lables

### ISSUE THREAD

**Issue by cardosojoao** [z00m128/sjasmplus#220]
| Version 	| Platform 	| Topic 	|
|---------	|----------	|-------	|
| v1.20.2 	|windows? 	| directive	|

I have some defines that I use to enable the custom location of some tables,  but when I enable both of them I get some duplicates messages
![image](https://github.com/z00m128/sjasmplus/assets/1773533/cae23c69-4af3-44e9-a728-7b33a748ab56)

duplicate messages
![image](https://github.com/z00m128/sjasmplus/assets/1773533/2d641f83-cfa5-4112-9e09-ce28a0029ec6)

I do have a test project that does the same and don't have any issues, but the project where I found the error is bigger around 12k lines and 188 files

```

```

**Comment by ped7g** [comment]
That's because the define `SetE_SpritesHW` is defined as empty string, and it exactly does match beginning of labels like `SetE_SpritesHW_Map_Address`, so it gets substituted by the sub-word matching.

To avoid it use define which does not match the part of labels, like
```
  DEFINE SET_E_SPRITES_HW
  IFDEF SET_E_SPRITES_HW
SetE_SpritesHW_Map_Address   equ $c180
...
  ENDIF
```
