### ISSUE TITLE
list file lines are one off in some cases

### ISSUE THREAD

**Issue by maziac** [z00m128/sjasmplus#23]
Let me first say that I'm a great fan of sjasmplus. It has so many cool features like fake-instructions, structures, local labels, good macro support.
So, I'm entering these bugs because I like to work with this assembler and hope that it will be improved further.
Please keep on the good work.

I now found a small problem with the listings file.
In some occasions the displayed line number is not correct, i.e. it is one-off and also all following lines are one off, too.
It happens when there is a local label used together with a ":"

This code here 
```
l1:
    nop
.end:
    nop
    nop
    nop
```

Results in
```
001   0000             l1: 
002   0000 00              nop
003   0001             .end
004   0001              
005   0001 00              nop
006   0002 00              nop
007   0003 00              nop
```
I.e. there is an extra line introduced after the .end label: line 4.

I works correctly if the local label is used without ":"
```
l1:
    nop
.end:
    nop
    nop
    nop
```

Result is OK:
```
001   0000             l1: 
002   0000 00              nop
003   0001             .end
004   0001 00              nop
005   0002 00              nop
006   0003 00              nop
```

Sorry, I can imagine that this sounds very pedantic.
The problem for me is because I use the list file in one of my projects, a Z80 debugger for vscode
(see https://github.com/maziac/z80-debug).
And currently I'm adding support for sjasmplus.
If the lines are one off in the list file, the lines are also one-off when stepping through the code in the debugger.

**Comment by z00m128** [comment]
Fixed in https://github.com/z00m128/sjasmplus/commit/eaf65ea057603afe391c11895e7373d865ec6b3f.
