### ISSUE TITLE
commandline: -D not working if more than one asm file

### ISSUE THREAD

**Issue by maziac** [z00m128/sjasmplus#24]
I tried to use a define on the commandline and this was working fine.
Then I added another source file and the define is not available in the files anymore.
E.g.
```
sjasmplus -DMY_DEFINE=1 a.asm
```
=> the define is available in a.asm

But
```
sjasmplus -DMY_DEFINE=1 a.asm b.asm
```
=> the define is not available in a.asm

**Comment by z00m128** [comment]
Fixed in https://github.com/z00m128/sjasmplus/commit/9ec27dc7ea258a5ad2702f0639d77a40219b92f8.
