### ISSUE TITLE
Installing on MacOS Error - fatal error: 'LuaBridge/LuaBridge.h' file not found

### ISSUE THREAD

**Issue by joegasewicz** [z00m128/sjasmplus#242]
| Version 	| Platform 	| Topic 	|
|---------	|----------	|-------	|
| v1.20.3 	| Apple M1 Pro	 (OS: 14.5)| Install error	|

Steps:
1. Clone the repo.
2. `cd` into `sjasmplus` directory
3. Run `make clean` ✅
4. Run `make` 💥

Error:
```
sjasm/lua_sjasm.cpp:35:10: fatal error: 'LuaBridge/LuaBridge.h' file not found
#include "LuaBridge/LuaBridge.h"
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [build/release/sjasm/lua_sjasm.o] Error 1
make: *** [install_sjasmplus] Error 2
```

**Comment by joegasewicz** [comment]
This solves it for me:

```
cd apps \
&& git clone https://github.com/z00m128/sjasmplus.git && \
cd sjasmplus \
&& git submodule update --init --force --remote\
&& make clean \
&& make \
&& sudo -S make install
```
The issue seems to be that the git submodule doesn't trigger an install of `LuaBridgez`:
```
[submodule "LuaBridge"]
	path = LuaBridge
	url = https://github.com/vinniefalco/LuaBridge.git
```

**Comment by ped7g** [comment]
The suggested way to get full repo is documented in [INSTALL.md](https:/z00m128/sjasmplus/blob/master/INSTALL.md#getting-full-source-code-of-sjasmplus): `git clone --recursive -j8 https://github.com/z00m128/sjasmplus.git`

or if cloned without submodules the `git submodule update --init --recursive` should fix it.

Can you try in new folders both documented ways, if they work as intended? If not, then it's something to look at in detail, why those fail. Thank you.

**Comment by ped7g** [comment]
I assume the documented sequence works, reopen in case it does not and show how it fails

**Comment by joegasewicz** [comment]
> The suggested way to get full repo is documented in [INSTALL.md](https:/z00m128/sjasmplus/blob/master/INSTALL.md#getting-full-source-code-of-sjasmplus): `git clone --recursive -j8 https://github.com/z00m128/sjasmplus.git`
> 
> or if cloned without submodules the `git submodule update --init --recursive` should fix it.
> 
> Can you try in new folders both documented ways, if they work as intended? If not, then it's something to look at in detail, why those fail. Thank you.

Yep that works, thank you
