### ISSUE TITLE
error: [IFDEF] No endif

### ISSUE THREAD

**Issue by asve79** [z00m128/sjasmplus#26]
| Version 	| Platform 	| Topic 	|
|---------	|----------	|-------	|
| v1.10.4 	| linux       | 	|

When building part of code:
```
       DEFINE  WC_PLUGIN 1

 ............................................ skip ...........................

	HALT

	IFDEF	WC_PLUGIN
	include "z80-sdk/wc_api/wind.a80"
	ELSE
	include "z80-sdk/windows_bmw/spkeyb40.a80"
	include "z80-sdk/windows_bmw/edznak.a80"
        include "z80-sdk/windows_bmw/wind.a80"
	include "z80-sdk/windows_bmw/dmm.a80"
        ENDIF
        include "main.asm"
```

Compiler get error:
```
startup.asm(88): error: [IFDEF] No endif
startup.asm(89): error: ENDIF without IF/IFN/IFUSED/IFNUSED/IFDEF/IFNDEF
```

**Comment by z00m128** [comment]
Please attach listing file from compilation, because it is unclear what you want to achieve. Looks like there is something wrong in the included files, because my similar test code (even with nested IFDEF/ELSE/ENDIF) works correctly.

**Comment by asve79** [comment]
Yes, looks like it was my mistake in included-included-included code. :(
One of module does not contain "endmodule" definition.
Sorry...

**Comment by z00m128** [comment]
No problem :-)
