### ISSUE TITLE
Allow calculation of pow(x,y)

### ISSUE THREAD

**Issue by maziac** [z00m128/sjasmplus#27]
**Is your feature request related to a problem?**
I would like to setup a frequency table for midi numbers to frequencies (AY8910 values).
Something like this:
```
midi_frequency_table:
midi_number=21
    dup 108-21+1
        defw (AY8910_CLOCK_FREQUENCY/16.0)/(pow(2,(midi_number-69)/12.0)*440)
midi_number=midi_number+1
    edup
````

**Describe the suggested solution:**
It would be nice if you could implement the power function, i.e.
pow(x,y) as x^y with floating point numbers.

**Comment by busy128** [comment]
You can use math.pow function in LUA script.
Example:

  LUA
  _pc(' dw ' .. math.pow(2,15))
  ENDLUA

**Comment by maziac** [comment]
This looks interesting.
Is it also possible to combine this with the EDUP and the variable midi_number, i.e.:

```
midi_number=21
    dup 108-21+1
LUA
_pc(' dw ' .. (AY8910_CLOCK_FREQUENCY/16.0)/(math.pow(2,(midi_number-69)/12.0)*440))
ENDLUA
midi_number=midi_number+1
    edup
```

**Comment by maziac** [comment]
I did it now with the following code:
 LUA ALLPASS
    for i=21, 127, 1
    do
        _pc(' dw ' .. math.floor((_c("AY8910_CLOCK_FREQUENCY")/16.0)/(math.pow(2,(i-69)/12.0)*440)))
    end
 ENDLUA

Note: AY8910_CLOCK_FREQUENCY is defined elsewhere as:
AY8910_CLOCK_FREQUENCY:     equ 1000000
