### ISSUE TITLE
Argument substitution not working with DEFINE names inside MACRO

### ISSUE THREAD

**Issue by Liniya** [z00m128/sjasmplus#45]
In a macro that sets a DEFINE with a name based on a macro argument, it appears that the argument is not being replaced with its value, and a define with the 'name of the macro argument' is set instead. In the following example, the define that ends up being set is 'name', not 'TESTD' as it should normally be. (The substitution seems to work correctly for the value of the define being set up).

```
	MACRO def name, val
	 DEFINE name val
	ENDM

	def TESTD, 12345
	
	IFDEF TESTD
	 DISPLAY /d, "'TESTD' is defined: ", TESTD
	ELSE
	 IFDEF name
	  DISPLAY /d, "'name' is defined: ", name
	 ENDIF
	ENDIF
```

**Comment by ped7g** [comment]
I think this is legitimate usage, where one would expect the term to substitute.

But the reason why it did not has also quite some valid background. I lifted the "don't substitute this" rule for macro arguments case, so now your example source should work as expected. But this also opens door for other incorrect sources (using this feature in incorrect way, like doing `def  TESTD, 123` after first one) to end with less logical error messages, making it harder to spot bug in the source.

But that's common issue with these C-preprocessor-like mechanisms, it's dangerously easy to unintentionally produce some bug by some small typo/etc. No idea how to fix it in better way.
