### ISSUE TITLE
INCTRD directive tests

### ISSUE THREAD

**Issue by ped7g** [z00m128/sjasmplus#47]
Could somebody with deeper TRD understanding add comprehensive example/test?
http://z00m128.github.io/sjasmplus/documentation.html#po_inctrd

I have suspicion the `offset` argument is incorrectly used, and there is -1 discrepancy introduced for non-zero offsets.

If somebody can verify this hypothesis and produce a test for the `INCTRD` directive, the fix would be simple (if there is bug).

**Comment by Liniya** [comment]
How about this? It will output the result to the console, you can probably change it if it's not what you want.

```
	IFNDEF _TRD_CREATED


	 DEVICE ZXSPECTRUM48

	 ORG #4000

String
	 DEFB "INCTRD test"
.len = $-String

	 EMPTYTRD "inctrd.trd"
	 SAVETRD "inctrd.trd","testfile.C",String,String.len

	 SHELLEXEC "sjasmplus.exe --raw=- -D_TRD_CREATED inctrd.asm" 
	

	ELSE


CTR = 0
	 DUP 8
	  INCTRD "inctrd.trd","testfile.C",CTR
CTR = CTR+1
	 EDUP


	ENDIF
```

And it seems the bug is there. Offset 1 is the same as 'no offset', and further on they are off by 1 like that.
