### ISSUE TITLE
Comments in macros removed from list file

### ISSUE THREAD

**Issue by maziac** [z00m128/sjasmplus#50]
Hi,

The following code

```
    MACRO m1
    ; commentA
    nop ; comment1
    ; commentB
    nop ; comment2
    nop ; comment3
    ENDM 

    ORG 0x8000

    m1 
```
produces
```
30    0005                  ORG 0x8000
31    8000
32    8000                  m1
32    8000             >    ; commentA
32    8000 00          >    nop
32    8001             >    ; commentB
32    8001 00          >    nop
32    8002 00          >    nop
```
in the list file.

The comments that are single on a line are still there but
the comments after the instructions have vanished.

I would assume that either no comments or all comments are written.
Preferable all comments would be written because I use some comments for instrumentation.

I did some further investigation. It seems that sometimes the comment after the instruction is simply taken from the comment of the line the macro has been used. E.g.
```
135+ B3C1                  _nextreg  0x50+1    ; 0x2000-0x3FFF
 135+ B3C1 ED 92       >        defb 0xED, 0x92; 0x2000-0x3FFF
 135+ B3C3 51          >        defb 0x50+1    ; 0x2000-0x3FFF
```
The comment  " ; 0x2000-0x3FFF" is simply repeated.

**Comment by ped7g** [comment]
yup, I know why this happens, but I have no simple fix for this at this moment :/ ...
I believe the comments are there at the macro definition? They are lost only upon macro emit? I think it current implementation will do that (as the emitting code doesn't have the comments any more, they were stripped during parsing, the comments in list file are from the stripping itself, which does not happen during emit ... and the stripped comment string is not cleared on emitted macro lines, so it does copy the leftover comment from previous real line.

For proper fix I will have to preserve the comments with macro lines, but not sure how to do it right now, will need to take deep look. (just simply leaving them in the line string will make the assembling fail, it does expect comment already stripped out).

**Comment by maziac** [comment]
OK, this explains why "comment1-3" is dropped but do you have an explanation why "commentA/B" is in.
For some reason these comments (without instructions) are left in.

BTW I can live with the current behaviour. I.e. I put the important comments in an own line in macros so they appear in the list file.

**Comment by ped7g** [comment]
I *guess* that only-comment lines are probably stored in macro lines storage as whole, and get rejected by other mechanism during assembling, so they don't fail and preserve. Didn't take a look on the code yet, but from what I recall how it looks, this sounds like what it probably does.

I hope I will be able to get back to this issue one day in future, as they real comment leaking into macro lines seems very wrong to me. Also preserving comments even on instruction lines seems like reasonable idea, although stripping comments upon macro emit can be sort of defended by some weird logic I guess (like shortening the source, while the comments are already at definition)... that sounds stupid. :D ... yep, it's a bugged either way, so thank you for reporting it.
