### ISSUE TITLE
Throw warnings on fake instructions

### ISSUE THREAD

**Issue by mborik** [z00m128/sjasmplus#7]
Modify the parser to **throw warnings on fake instructions**:
- alternatively on those which are most suspicious, for example `sub a,b`, but I prefer all of them
- probably there should be some kind of verbosity filter if there are too many fake instructions in source (so we need to throw it in the second pass)
- implement another command line parameter `--silentfakes` which dismiss those warnings _(in addition to already implemented `--nofakes`)_

**Comment by ped7g** [comment]
But `sub a,b` is not "fake" instruction in the sense of `--nofakes` switch. It's "multi-argument" feature emitting `sub a : sub b`.

So maybe adding warning for `sub` especially (if only two arguments, and first is `a`)...

Still adding warning about fake instructions, and/or warning about multi-arguments on some new switch is probably happen in some form sooner or later, as I really want something like `--strict` guarding also many other relaxed syntax quirks and warn/error about them. I'm just not sure how to catch `sub a,b` if one actually does want multi-arguments generally, but this one is typo.
