### ISSUE TITLE
SAVE3DOS pseudo-op

### ISSUE THREAD

**Issue by z00m128** [z00m128/sjasmplus#81]
A nice to have feature popped up in discussions: ability to export binaries with +3DOS header by pseudo-op `SAVE3DOS`. It is usable not only with ZX Next, but also for `LOAD*` command in ESXDOS.

**Comment by ped7g** [comment]
so.. can somebody do reconnaissance for me, how this header looks, and few binary examples, saving like CODE 34661 (0x8765). and basic programs with/without LINE xx?

**Comment by z00m128** [comment]
Attached files are created with ESXDOS 0.8.6: 
TEST1 = BASIC without autorun
TEST2 = BASIC with autorun LINE 10
TEST3 = CODE 34661,16384


Description found on internet: 

Offset | Length | Description
-- | -- | --
0 | 8 | "PLUS3DOS" identification text
8 | 1 | &1a marker byte (note 1)
9 | 1 | Issue number
10 | 1 | Version number
11 | 4 | Length of the file in bytes (note 2)
15..22 |   | +3 Basic header data
23..126 |   | Reserved (note 3)
127 |   | Checksum (note 4))

Notes:

    This byte is used by C/PM to mark the end of a file. It is called the "soft end of file". The "hard end of file" describes the length of the file in complete sectors. There may be additional bytes (which are ignored), between the position marked by the "soft end of file" and the position marked by the "hard end of file".
    The length of the file is a 32 bit number.
        The byte at offset 11 contains bit 7..0 of the value,
        The byte at offset 12 contains bits 15..8 of the value,
        The byte at offset 13 contains bits 23..16 of the value,
        The byte at offset 14 contains bits 32..24 of the value 
    These bytes are reserved for a future use. Set these bytes to 0 when creating files with this header
    The checksum is generated from the sum of the bytes 0..126. This value is the low 8 bits (bit 7..0) of the calculated value. 

[plus3dos-header-examples.zip](https://github.com/z00m128/sjasmplus/files/3635582/plus3dos-header-examples.zip)

**Comment by z00m128** [comment]
And this is corresponding section from ZXS128 +3 manual:

File headers

Tape files have headers which contain some system information. +3DOS
files may, or may not, have headers. All files created by BASIC's SAVE
command will have headers.

The +3DOS header mechanism provides a dedicated 8 byte area in each
headed file reserved for BASIC's use. The remainder of the header is
reserved for +3DOS. This 8 byte header is utilised in files created by
BASIC commands (see DOS OPEN description).

+3DOS files may have a single header in the first 128 bytes of the
file - the header record. These headers are detected by a 'signature'
and checksum. If the signature and checksum are as expected, then a
header is present; if not, these is no header. Thus, it is possible,
but unlikely, that a file without a header could be mistaken for one
with a header.

The format of the header record is as follows:

	Bytes 0...7	- +3DOS signature - 'PLUS3DOS'
	Byte 8		- 1Ah (26) Soft-EOF (end of file)
	Byte 9		- Issue number
	Byte 10		- Version number
	Bytes 11...14	- Length of the file in bytes, 32 bit number,
			    least significant byte in lowest address
	Bytes 15...22	- +3 BASIC header data
	Bytes 23...126	- Reserved (set to 0)
	Byte 127	- Checksum (sum of bytes 0...126 modulo 256)

The issue and version numbers are provided for any future
expansion. The issue number must equal the software's issue number;
the version number must be less than or equal to the software's
version number.

+3DOS performs all the necessary header 'house-keeping'. A pointer to
+3 BASIC's 8 byte header area may be returned using DOS REF HEAD. It
is never necessary to write directly to the 128 byte header.

AMSDOS headers (as used on the AMSTRAD CPC range of computers) will
not be recognised. AMSDOS files will be treated by +3DOS as
headerless, and vice versa.
