### ISSUE TITLE
UNDEFINE pseudo-op is not working as expected

### ISSUE THREAD

**Issue by z00m128** [z00m128/sjasmplus#9]
The manual says: _UNDEFINE <id> ... Removes the identifier defined by DEFINE_, but it undefines all defines.

Bug indentified by busy in _sjasm/tables.cpp_. Proposed fix: insert
_if (p && !strcmp(name, p->name)) {defs[(unsigned char)*name] = p->next;} else_ 
before line _215_ (starts with _while (*p) {_)

**Comment by mborik** [comment]
Resolved by #10 in 612fcc8
