### ISSUE TITLE
SAVESNA SP content

### ISSUE THREAD

**Issue by maziac** [z00m128/sjasmplus#96]
This is more a question than a bug/issue.

E.g. see this example and create a SNA file with sjasmplus:
~~~
   DEVICE ZXSPECTRUM48

start_address:     EQU 0x8000
                ORG start_address

		ld hl, 16384
		ld (hl), 255
		ret
		
                SAVESNA "file.sna", start_address
~~~

I noticed while debugging that the first value on the stack is not the value start_address given with 
SAVESNA "file.sna", start_address but a pointer to a location in ROM 0x33B1.
After stepping through the code and some RETs one will eventually end up at start_address,
so everything is working fine. But, why is this. Why does the location where the SP points to does
not directly include the start_address?

The "negative" effect is that if you start such a file in z80-debug/zesarux it will at first show address 0x33B1 to the user
and not the start of his program. I.e. it looks like something is going wrong.

(Maybe this is related to "better fake sysvars+stack for snapshots #95")

**Comment by ped7g** [comment]
I don't know, I don't think I modified the mechanism in principle back when I was adjusting code around this, so I believe the mechanics are still same as in older sjasmplus versions and I have no insight into the original idea. Maybe setting up HL+DE through common ROM code.

Anyway, yes, it's related to #95 and Busy gave me already some new sysvars and stack values and how-to use them, so I guess this will be modified after fixing 95. While changes like these may eventually break someone's project (and thus it will be released as new minor version 1.15.0), I generally have high confidence into Busy's expertise and I expect the new changes to work in 90% of cases better than current ones.

**Comment by ped7g** [comment]
The default "full fake stack" for 48k snapshot will now start directly at start_address.
All the use-cases I'm aware of seems to work well, but I'm not sure if there's some more magic hidden in old way to support maybe some TR-DOS specifics on the clone machines, but I have no idea - I will push the new style in v1.15.0 and wait for error reports, if it breaks something... :)

The DEVICE directive now allows also to set RAMTOP variable, which means you can finally affect stack-pointer location for snapshots.

**Comment by maziac** [comment]
Very good. Thank you.
